version: '3'
services:
  movie:
    image: joshipavan316/phonepaymovies:v1
    ports:
      - "8000:80"
    deploy:
      replicas: 4    
  
  train:
    image: joshipavan316/phonepaytrains:v1
    ports:
      - "8001:80"
    deploy:
      replicas: 4
    
  recharge:
    image: joshipavan316/phonepayrecharges:v1
    ports:
      - "8002:80"
    deploy:
      replicas: 4 


